"""add timeseries

Revision ID: a2104567304e
Revises: 
Create Date: 2017-04-24 23:11:43.629704

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a2104567304e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('time_series',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('value', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_time_series_name'), 'time_series', ['name'], unique=False)
    op.create_index(op.f('ix_time_series_timestamp'), 'time_series', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_time_series_timestamp'), table_name='time_series')
    op.drop_index(op.f('ix_time_series_name'), table_name='time_series')
    op.drop_table('time_series')
    # ### end Alembic commands ###
